import Mathlib

/-!
# Quotient block occupancy for independent eligible-color matchings

This file develops the finite sector model used by the independent-matching
welded-tree argument.  A sector fixes every item except the names of the
visited blocks.  The remaining coordinates range over finite sets of blocks;
legal placements are the injective ones.  Rooted colorword generators become
coordinate-fiber vectors.

No proof placeholder or user-defined axiom is used.
-/

open scoped BigOperators

namespace IndependentMatchingBlockOccupancy

/-- Finite data left after fixing all root-independent information in one
strongly noncolliding observed-forest sector. -/
structure SectorData (d B : ℕ) where
  orbit : Fin d → Finset (Fin B)
  compat : Fin d → Finset (Fin B)
  compat_subset : ∀ i, compat i ⊆ orbit i
  orbit_nonempty : ∀ i, (orbit i).Nonempty

namespace SectorData

variable {d B : ℕ} (S : SectorData d B)

/-- A placement before block collisions are removed.  Coordinate `i` is
literally an element of its structural orbit. -/
abbrev RawPlacement := ∀ i : Fin d, {a : Fin B // a ∈ S.orbit i}

/-- The actual block name carried by one coordinate. -/
def block (x : S.RawPlacement) (i : Fin d) : Fin B := (x i).1

/-- A legal placement uses no actual block twice. -/
def Legal (x : S.RawPlacement) : Prop := Function.Injective (S.block x)

/-- Placements remaining after collision deletion. -/
abbrev Placement := {x : S.RawPlacement // S.Legal x}

/-- Real amplitudes on the product table. -/
abbrev RawVector := S.RawPlacement → ℝ

/-- Real amplitudes on the legal placement table. -/
abbrev Vector := S.Placement → ℝ

/-- The unnormalized indicator of a coordinate fiber in the product table. -/
noncomputable def rawFiber (i : Fin d) (a : Fin B) : S.RawVector :=
  fun x => if S.block x i = a then 1 else 0

/-- The same fiber after restricting to legal placements. -/
noncomputable def fiber (i : Fin d) (a : Fin B) : S.Vector :=
  fun x => if S.block x.1 i = a then 1 else 0

/-- Restriction from the product table to legal placements. -/
def restrict (f : S.RawVector) : S.Vector := fun x => f x.1

@[simp] theorem restrict_rawFiber (i : Fin d) (a : Fin B) :
    S.restrict (S.rawFiber i a) = S.fiber i a := by
  rfl

/-- A rooting family is structurally complete when every block in its orbit
supports that rooted description. -/
def Complete (i : Fin d) : Prop := S.compat i = S.orbit i

/-- The coordinate-`i` cylinder at the distinguished block. -/
noncomputable def atU (u : Fin B) (i : Fin d) : S.Vector := S.fiber i u

/-- Product-table counterpart of `atU`. -/
noncomputable def rawAtU (u : Fin B) (i : Fin d) : S.RawVector := S.rawFiber i u

/-- The sector contribution generated by descriptions whose root is at `u`. -/
noncomputable def insideSpace (u : Fin B) : Submodule ℝ S.Vector :=
  Submodule.span ℝ
    {f | ∃ i : Fin d, u ∈ S.compat i ∧ f = S.fiber i u}

/-- The sector contribution generated by descriptions whose root is not at
`u`. -/
noncomputable def outsideSpace (u : Fin B) : Submodule ℝ S.Vector :=
  Submodule.span ℝ
    {f | ∃ (i : Fin d) (a : Fin B), a ∈ S.compat i ∧ a ≠ u ∧
      f = S.fiber i a}

/-- Unnormalized Euclidean inner product on the legal table. -/
noncomputable def inner (f g : S.Vector) : ℝ := ∑ x, f x * g x

/-- Membership in the true quotient
`H_{¬u} \ominus (H_u ∩ H_{¬u})`. -/
def InOutsideQuotient (u : Fin B) (f : S.Vector) : Prop :=
  f ∈ S.outsideSpace u ∧
    ∀ g, g ∈ S.insideSpace u → g ∈ S.outsideSpace u → S.inner f g = 0

/-- Occupancy of `u` by any free block coordinate. -/
def Occupied (u : Fin B) (x : S.Placement) : Prop :=
  ∃ i, S.block x.1 i = u

/-- Squared mass on legal placements occupying `u`. -/
noncomputable def occupiedEnergy (u : Fin B) (f : S.Vector) : ℝ := by
  classical
  exact ∑ x, if S.Occupied u x then (f x) ^ 2 else 0

/-- Total squared mass on the legal table. -/
noncomputable def totalEnergy (f : S.Vector) : ℝ := ∑ x, (f x) ^ 2

private theorem sum_fibers_pointwise (x : S.Placement) (i : Fin d) :
    (∑ a ∈ S.orbit i, S.fiber i a x) = 1 := by
  classical
  let b : Fin B := S.block x.1 i
  have hb : b ∈ S.orbit i := (x.1 i).2
  rw [Finset.sum_eq_single b]
  · simp [fiber, b]
  · intro a ha hab
    simp [fiber, b, Ne.symm hab]
  · exact fun h => (h hb).elim

private theorem sum_rawFibers_pointwise (x : S.RawPlacement) (i : Fin d) :
    (∑ a ∈ S.orbit i, S.rawFiber i a x) = 1 := by
  classical
  let b : Fin B := S.block x i
  have hb : b ∈ S.orbit i := (x i).2
  rw [Finset.sum_eq_single b]
  · simp [rawFiber, b]
  · intro a ha hab
    simp [rawFiber, b, Ne.symm hab]
  · exact fun h => (h hb).elim

/-- The sum of all fibers of one coordinate is the all-ones vector. -/
theorem sum_fibers_eq_one (i : Fin d) :
    (∑ a ∈ S.orbit i, S.fiber i a) = (1 : S.Vector) := by
  classical
  funext x
  simpa using S.sum_fibers_pointwise x i

/-- Product-table version of `sum_fibers_eq_one`. -/
theorem sum_rawFibers_eq_one (i : Fin d) :
    (∑ a ∈ S.orbit i, S.rawFiber i a) = (1 : S.RawVector) := by
  classical
  funext x
  simpa using S.sum_rawFibers_pointwise x i

/-- Sum of all non-`u` fibers from a complete family. -/
noncomputable def outsideSum (u : Fin B) (i : Fin d) : S.Vector :=
  ∑ a ∈ (S.orbit i).erase u, S.fiber i a

/-- The same sum on the product table. -/
noncomputable def rawOutsideSum (u : Fin B) (i : Fin d) : S.RawVector :=
  ∑ a ∈ (S.orbit i).erase u, S.rawFiber i a

/-- Every term in `outsideSum` is an outside generator when the family is
complete. -/
theorem outsideSum_mem_outside (u : Fin B) (i : Fin d)
    (hi : S.Complete i) : S.outsideSum u i ∈ S.outsideSpace u := by
  classical
  unfold outsideSum
  apply Submodule.sum_mem
  intro a ha
  apply Submodule.sum_mem
  intro _ hmem
  apply Submodule.subset_span
  refine ⟨i, a, ?_, ?_, rfl⟩
  · simpa [Complete, hi] using (Finset.mem_of_mem_erase hmem)
  · exact (Finset.ne_of_mem_erase hmem)

/-- The distinguished cylinder is an inside generator for a complete family
whose orbit contains `u`. -/
theorem atU_mem_inside (u : Fin B) (i : Fin d)
    (hi : S.Complete i) (hui : u ∈ S.orbit i) :
    S.atU u i ∈ S.insideSpace u := by
  apply Submodule.subset_span
  refine ⟨i, ?_, rfl⟩
  simpa [Complete, hi] using hui

/-- If `u` belongs to an orbit, the non-`u` fiber sum equals `1 - atU`. -/
theorem outsideSum_eq_one_sub_atU (u : Fin B) (i : Fin d)
    (hui : u ∈ S.orbit i) :
    S.outsideSum u i = (1 : S.Vector) - S.atU u i := by
  classical
  have hsum := S.sum_fibers_eq_one i
  rw [← Finset.sum_erase_add _ _ hui] at hsum
  simp only [outsideSum, atU] at hsum ⊢
  rw [← hsum]
  abel

/-- If `u` is absent from an orbit, the outside sum is the all-ones vector. -/
theorem outsideSum_eq_one_of_not_mem (u : Fin B) (i : Fin d)
    (hui : u ∉ S.orbit i) :
    S.outsideSum u i = (1 : S.Vector) := by
  classical
  unfold outsideSum
  rw [Finset.erase_eq_of_not_mem hui]
  exact S.sum_fibers_eq_one i

/-- Exact common-direction identity for two complete rooting families. -/
theorem atU_sub_atU_eq_outsideSums (u : Fin B) (i j : Fin d)
    (hui : u ∈ S.orbit i) (huj : u ∈ S.orbit j) :
    S.atU u i - S.atU u j = S.outsideSum u j - S.outsideSum u i := by
  rw [S.outsideSum_eq_one_sub_atU u i hui,
    S.outsideSum_eq_one_sub_atU u j huj]
  abel

/-- The difference of two complete `u`-fibers lies in both actual sector
spaces.  This is the corrected exact-intersection statement. -/
theorem completeDifference_mem_inter (u : Fin B) (i j : Fin d)
    (hi : S.Complete i) (hj : S.Complete j)
    (hui : u ∈ S.orbit i) (huj : u ∈ S.orbit j) :
    S.atU u i - S.atU u j ∈
      S.insideSpace u ⊓ S.outsideSpace u := by
  rw [Submodule.mem_inf]
  constructor
  · exact Submodule.sub_mem _
      (S.atU_mem_inside u i hi hui) (S.atU_mem_inside u j hj huj)
  · rw [S.atU_sub_atU_eq_outsideSums u i j hui huj]
    exact Submodule.sub_mem _
      (S.outsideSum_mem_outside u j hj)
      (S.outsideSum_mem_outside u i hi)

/-- A complete family whose orbit avoids `u` supplies the constant function
inside the outside space. -/
theorem one_mem_outside_of_complete_avoiding (u : Fin B) (h : Fin d)
    (hh : S.Complete h) (huh : u ∉ S.orbit h) :
    (1 : S.Vector) ∈ S.outsideSpace u := by
  rw [← S.outsideSum_eq_one_of_not_mem u h huh]
  exact S.outsideSum_mem_outside u h hh

/-- If one complete family avoids `u`, every complete `u`-fiber is itself an
exact common vector. -/
theorem completeAtU_mem_inter_of_avoiding (u : Fin B) (i h : Fin d)
    (hi : S.Complete i) (hh : S.Complete h)
    (hui : u ∈ S.orbit i) (huh : u ∉ S.orbit h) :
    S.atU u i ∈ S.insideSpace u ⊓ S.outsideSpace u := by
  rw [Submodule.mem_inf]
  constructor
  · exact S.atU_mem_inside u i hi hui
  · have hone := S.one_mem_outside_of_complete_avoiding u h hh huh
    have hout := S.outsideSum_mem_outside u i hi
    rw [S.outsideSum_eq_one_sub_atU u i hui] at hout
    have hsub := Submodule.sub_mem _ hone hout
    simpa using hsub

end SectorData

end IndependentMatchingBlockOccupancy
